-- Run as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS DASHROUTE_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND  = 60
  AUTO_RESUME   = TRUE
  INITIALLY_SUSPENDED = FALSE;

USE WAREHOUSE DASHROUTE_WH;
