USE DATABASE DASHROUTE_DB;
USE SCHEMA MVP_SCHEMA;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID    VARCHAR   DEFAULT UUID_STRING(),
    USERNAME   VARCHAR   NOT NULL,
    POINTS     INTEGER   DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS SUBMISSIONS (
    SUBMISSION_ID VARCHAR DEFAULT UUID_STRING(),
    USER_ID       VARCHAR NOT NULL,
    FILE_NAME     VARCHAR NOT NULL,
    HAZARD_TYPE   VARCHAR DEFAULT 'PENDING',
    STATUS        VARCHAR DEFAULT 'PENDING',
    UPLOADED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUBMISSION_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Seed a demo user
INSERT INTO USERS (USERNAME, POINTS)
VALUES ('HackathonHero_01', 50);
